name: CD — Production

concurrency:
  group: production
  cancel-in-progress: true

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    environment:
      name: production
      # url: https://staging.includedavis.com
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Lint code
        run: yarn lint

      - name: Publish to Netlify
        run: netlify deploy --build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
