name: CD

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Lint code
        run: yarn lint
        
      - name: Build
        run: yarn build

      - name: Publish to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
